### ISSUE TITLE
Sector-24, 50 Mbps Airtel Internet Link is down

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Internet#1]
Sector-24, 50 Mbps Airtel Internet Link is down call logged to Airtel Case id 28099925
@msrawat-isgec @vinay-isgec @Isgec/dc-infra-team

**Comment by praveen-isgec** [comment]
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by praveen-isgec** [comment]
Discussed with Airtel Back end team, he is aligned field engineer for the same.

 

Regards

M.S.Rawat

 

From: Praveen Kumar [mailto:praveen1.kumar@isgec.co.in] 
Sent: Monday, January 11, 2021 2:22 PM
To: 'DCADMIN'
Cc: 'Isgec/ITIL-Internet'
Subject: RE: [Isgec/ITIL-Internet] Sector-24, 50 Mbps Airtel Internet Link is down (#1)

 

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by msrawat-isgec** [comment]
Now link is working

**Comment by msrawat-isgec** [comment]
Now  link is working

 

 

Nagios Status.



 

Regards

M.S.Rawat

**Comment by msrawat-isgec** [comment]
Airtel Engineer changed MUX PRI Card and Internet is working fine.

Dear Sir Please close the Case @dhirendra-isgec
