### ISSUE TITLE
Sec-24 Firewall require restart

### ISSUE THREAD

**Issue by vinay-isgec** [Isgec/ITIL-Internet#3]
it is observed GST Site not working in commercial department.  Earlier its works.  
we are making plan to restart Firewall in lunch time during 1:15 PM to 1:45 PM, for checking the issue.
@Isgec/dc-infra-team , myself working on it

**Comment by dhirendra-isgec** [comment]
Is it resolved now after restarting the firewall.

**Comment by vinay-isgec** [comment]
No sir, we are adding the following IP address in full internet access group policy.  Because the site is working on above  IPs 192.168.28.200 

 

192.168.28.63

192.168.28.33 

192.168.28.114

192.168.28.41

192.168.28.156

 

 

 

Regards

Vinay

**Comment by dhirendra-isgec** [comment]
Any issue reported today
